- name: update apt packages
  apt: update_cache=yes
      force_apt_get=yes
      cache_valid_time=3600

- name: upgrade apt packages
  apt:
      upgrade: yes

- name: remove non-required dependencies
  apt:
      autoremove: yes
